# Generated by Django 4.2.8 on 2023-12-17 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_favoritos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favoritos',
            new_name='Favorito',
        ),
        migrations.RenameModel(
            old_name='Locais',
            new_name='Local',
        ),
    ]
